### ISSUE TITLE
Standardize traceroute websocket call.

### ISSUE THREAD

**Issue by pbootly** [pbootly/transitbuster#5]
We need to determine what the traceroute websocket call will look like, then implement it in both frontend and backend.

**Comment by Unaidedsteak** [comment]
Thinking a simple delimiter or something like "Traceroute | <IP>" e.g Traceroute | 10.10.1.121 
Thoughts?

**Comment by pbootly** [comment]
As per last commit - are you happy with `:` as the delim? If you look at current daemon.js this works.

**Comment by Unaidedsteak** [comment]
Yep 👍
