### ISSUE TITLE
Determine what process does GeoIP lookup

### ISSUE THREAD

**Issue by pbootly** [pbootly/transitbuster#6]

**Comment by Unaidedsteak** [comment]
Not sure if this is relevant to this issue (No description) but I've implemented a simple get request to http://freegeoip.net for geoIP data and am plotting a marker (flag in the image below) based on the locations it returns: 

![image](https://user-images.githubusercontent.com/14805497/34027488-feca9b4e-e154-11e7-88ec-17358f78169e.png)
