### ISSUE TITLE
Determine MAP solution that will work within the VUE environment

### ISSUE THREAD

**Issue by pbootly** [pbootly/transitbuster#7]

**Comment by Unaidedsteak** [comment]
I've implemented google maps, It should work fine however i have the following concerns: 
- Requires API key, added complexity for users. 
- Doesn't seem to be an easy way to animate a line or do anything special really. Could potentially use SVG for this still. 

Here's current styling: 

![image](https://user-images.githubusercontent.com/14805497/34025940-a6cc05d6-e14a-11e7-95fe-217dfb0c76a3.png)

Thoughts?

**Comment by pbootly** [comment]
Plus all of the ones
